[[redirects]]
from = "/discord"
to = "https://discord.gg/9uxgxHY3pP"

[[redirects]]
from = "/facebook"
to = "https://www.facebook.com/CPMSoc/"

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/cpmsoc_unsw/"

[[redirects]]
from = "/newsletter"
to = "https://forms.gle/L9VeEY8ZDqYKDyha6"

[[redirects]]
from = "/apply"
to = "https://forms.gle/2ppFkLYxngP16dxi9"

[[redirects]]
from = "/attendance"
to = "https://forms.gle/VKT3GeYGrZtFu4CQA"

[[redirects]]
from = "/feedback"
to = "https://forms.gle/a8TAMjrpEWSD3TWj6"

