[[redirects]]
from = "/discord"
to = "https://discord.gg/9uxgxHY3pP"

[[redirects]]
from = "/facebook"
to = "https://www.facebook.com/CPMSoc/"

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/cpmsoc_unsw/"

[[redirects]]
from = "/newsletter"
to = "https://docs.google.com/forms/d/e/1FAIpQLSeXwTqSzbHGxlwypQBhtEZlbdYroEBb_7-bUpM9nsTfIP4wtg/viewform?usp=sf_link"

